packages:
  - .
  - plugins

onlyBuiltDependencies:
  - '@parcel/watcher'
  - detox
  - dprint
  - dtrace-provider
  - esbuild
  - expo-filesystem-android-external-storage
  - less
  - svelte-preprocess
  - unrs-resolver

patchedDependencies:
  isomorphic-git: patches/isomorphic-git.patch
