packages:
  - .
  - plugins

allowBuilds:
  '@ipshipyard/node-datachannel': true
  '@parcel/watcher': false
  detox: true
  dprint: false
  dtrace-provider: false
  esbuild: false
  less: false
  svelte-preprocess: true
  unrs-resolver: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - detox
  - dprint
  - dtrace-provider
  - esbuild
  - expo-tiddlywiki-filesystem-android-external-storage
  - less
  - svelte-preprocess
  - unrs-resolver
