// Auto-generated by buildTiddlyWikiAssets.mjs from $tw.config.contentTypeInfo.
// Maps tiddler type → { encoding, extension } for determining on-disk file format.
// This is generated at build time by extracting the registerFileType() registrations
// from the bundled TW core, so plugin-added types are automatically included.

// Generated: 2026-06-13T06:23:43.749Z
// TiddlyWiki version: 5.4.0

export interface ContentTypeInfoEntry {
  encoding: 'utf8' | 'base64' | 'utf16le';
  /** File extension with leading dot (e.g. '.tid', '.md', '.png'). May be an array. */
  extension: string | string[];
}

const contentTypeInfo: Record<string, ContentTypeInfoEntry> = {
  'text/vnd.tiddlywiki': { encoding: 'utf8', extension: '.tid' },
  'application/x-tiddler': { encoding: 'utf8', extension: '.tid' },
  'application/x-tiddlers': { encoding: 'utf8', extension: '.multids' },
  'application/x-tiddler-html-div': { encoding: 'utf8', extension: '.tiddler' },
  'text/vnd.tiddlywiki2-recipe': { encoding: 'utf8', extension: '.recipe' },
  'text/plain': { encoding: 'utf8', extension: '.txt' },
  'text/css': { encoding: 'utf8', extension: '.css' },
  'text/html': { encoding: 'utf8', extension: '.html' },
  'application/hta': { encoding: 'utf16le', extension: '.hta' },
  'application/javascript': { encoding: 'utf8', extension: '.js' },
  'application/json': { encoding: 'utf8', extension: '.json' },
  'application/pdf': { encoding: 'base64', extension: '.pdf' },
  'application/zip': { encoding: 'base64', extension: '.zip' },
  'application/x-zip-compressed': { encoding: 'base64', extension: '.zip' },
  'image/jpeg': { encoding: 'base64', extension: '.jpg' },
  'image/jpg': { encoding: 'base64', extension: '.jpg' },
  'image/png': { encoding: 'base64', extension: '.png' },
  'image/gif': { encoding: 'base64', extension: '.gif' },
  'image/webp': { encoding: 'base64', extension: '.webp' },
  'image/heic': { encoding: 'base64', extension: '.heic' },
  'image/heif': { encoding: 'base64', extension: '.heif' },
  'image/avif': { encoding: 'base64', extension: '.avif' },
  'image/svg+xml': { encoding: 'utf8', extension: '.svg' },
  'image/vnd.microsoft.icon': { encoding: 'base64', extension: '.ico' },
  'image/x-icon': { encoding: 'base64', extension: '.ico' },
  'application/wasm': { encoding: 'base64', extension: '.wasm' },
  'font/woff': { encoding: 'base64', extension: '.woff' },
  'font/woff2': { encoding: 'base64', extension: '.woff2' },
  'font/ttf': { encoding: 'base64', extension: '.ttf' },
  'font/otf': { encoding: 'base64', extension: '.otf' },
  'audio/ogg': { encoding: 'base64', extension: '.ogg' },
  'audio/mp4': { encoding: 'base64', extension: '.mp4' },
  'video/ogg': { encoding: 'base64', extension: '.ogm' },
  'video/webm': { encoding: 'base64', extension: '.webm' },
  'video/mp4': { encoding: 'base64', extension: '.mp4' },
  'audio/mp3': { encoding: 'base64', extension: '.mp3' },
  'audio/mpeg': { encoding: 'base64', extension: '.mp3' },
  'text/markdown': { encoding: 'utf8', extension: '.md' },
  'text/x-markdown': { encoding: 'utf8', extension: '.md' },
  'application/enex+xml': { encoding: 'utf8', extension: '.enex' },
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': { encoding: 'base64', extension: '.docx' },
  'application/msword': { encoding: 'base64', extension: '.doc' },
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': { encoding: 'base64', extension: '.xlsx' },
  'application/excel': { encoding: 'base64', extension: '.xls' },
  'application/vnd.ms-excel': { encoding: 'base64', extension: '.xls' },
  'application/vnd.openxmlformats-officedocument.presentationml.presentation': { encoding: 'base64', extension: '.pptx' },
  'application/mspowerpoint': { encoding: 'base64', extension: '.ppt' },
  'text/x-bibtex': { encoding: 'utf8', extension: '.bib' },
  'application/x-bibtex': { encoding: 'utf8', extension: '.bib' },
  'application/epub+zip': { encoding: 'base64', extension: '.epub' },
  'application/octet-stream': { encoding: 'base64', extension: '.octet-stream' },
};

export default contentTypeInfo;

/**
 * Get the file extension (with leading dot, e.g. `.tid`, `.md`) for a tiddler type.
 * Falls back to '.tid' for unknown or untyped tiddlers.
 */
export function getExtensionForType(tiddlerType: string | undefined): string {
  if (!tiddlerType) return '.tid';
  const entry = contentTypeInfo[tiddlerType] as ContentTypeInfoEntry | undefined;
  if (!entry) return '.tid';
  return Array.isArray(entry.extension) ? entry.extension[0] : entry.extension;
}

/**
 * Whether a tiddler type stores body and metadata as separate files.
 * Desktop TW writes .tid as self-contained (header+body), and every other
 * extension as body-only + .meta companion.
 */
export function usesSeparateMetaFile(tiddlerType: string | undefined): boolean {
  return getExtensionForType(tiddlerType) !== '.tid';
}

/**
 * Get the file encoding for a tiddler type's body file.
 * Desktop TW passes this to fs.writeFile for binary-safe writes.
 * Falls back to 'utf8' for unknown types.
 */
export function getTypeEncoding(tiddlerType: string | undefined): 'utf8' | 'base64' {
  if (!tiddlerType) return 'utf8';
  const entry = contentTypeInfo[tiddlerType] as ContentTypeInfoEntry | undefined;
  if (!entry) return 'utf8';
  return entry.encoding === 'base64' ? 'base64' : 'utf8';
}
