/**
 * Pre-build TiddlyWiki empty HTML at development/CI time using TW's own render engine.
 * This renders `$:/core/save/empty` which produces a complete HTML with boot kernel + system tiddlers ($:/core, themes) embedded in the store area.
 *
 * Usage: zx scripts/buildTiddlyWikiAssets.mjs
 *
 * Output:
 *   assets/tiddlywiki/tiddlywiki-empty.html — complete boot HTML with $:/core + themes embedded
 */

import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';
import { mkdirSync, writeFileSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');
const require = createRequire(import.meta.url);

/**
 * Resolve the tiddlywiki npm package root directory.
 * Only uses npm — no workspace repo fallback, so CI works identically to local dev.
 */
function findTiddlyWikiPath() {
  const bootPath = require.resolve('tiddlywiki/boot/boot.js');
  const twPath = resolve(bootPath, '..', '..');
  console.log('Using TiddlyWiki npm package:', twPath);
  return twPath;
}

/**
 * Boot TiddlyWiki with the empty edition and return the $tw object.
 * The empty edition includes $:/core + vanilla/snowwhite themes.
 */
function bootTiddlyWiki(twPath) {
  return new Promise((resolve, reject) => {
    try {
      const $tw = require(twPath + '/boot/boot.js').TiddlyWiki();
      $tw.boot.argv = [twPath + '/editions/empty'];
      $tw.boot.boot(function() {
        resolve($tw);
      });
    } catch (error) {
      reject(error);
    }
  });
}

// ─── Main ──────────────────────────────────────────────────────────────────────

const twPath = findTiddlyWikiPath();
console.log('Booting TiddlyWiki from empty edition...');
const $tw = await bootTiddlyWiki(twPath);
console.log('TiddlyWiki booted, version:', $tw.version);

// Use TW's own rendering engine to render $:/core/save/empty
// This produces a complete HTML with: boot kernel + system tiddler store (core + themes)
const emptyHtml = $tw.wiki.renderTiddler('text/plain', '$:/core/save/empty');
console.log(`Rendered $:/core/save/empty: ${(emptyHtml.length / 1024).toFixed(1)} KB`);

// Write the single HTML asset
const outDir = resolve(projectRoot, 'assets', 'tiddlywiki');
mkdirSync(outDir, { recursive: true });

const htmlPath = resolve(outDir, 'tiddlywiki-empty.html');
writeFileSync(htmlPath, emptyHtml, 'utf8');
console.log(`Wrote ${htmlPath} (${(emptyHtml.length / 1024 / 1024).toFixed(2)} MB)`);

// Write version info for CopyDebugInfoButton
const versionInfo = {
  tiddlywikiVersion: $tw.version,
  buildDate: new Date().toISOString(),
};
const versionPath = resolve(outDir, 'version.json');
writeFileSync(versionPath, JSON.stringify(versionInfo, null, 2), 'utf8');
console.log(`Wrote ${versionPath}`);

// Write content-type-info module for mobile-side file extension lookups.
// This allows the mobile FS adaptor to determine the correct file extension
// for ANY tiddler type (not just hardcoded markdown), matching desktop's
// $tw.utils.generateTiddlerFileInfo behavior.
const contentTypeInfoPath = resolve(projectRoot, 'src', 'services', 'WikiStorageService', 'contentTypeInfo.ts');
const contentTypeInfo = $tw.config.contentTypeInfo;
const entries = Object.entries(contentTypeInfo).map(([type, info]) => {
  const { encoding, extension, ...rest } = info;
  const extStr = JSON.stringify(extension);
  // Use single quotes for TS code style (dprint compatibility)
  return `  '${type}': { encoding: '${encoding}', extension: ${extStr.replace(/"/g, "'")} }`;
});
const tsContent = [
  '// Auto-generated by buildTiddlyWikiAssets.mjs from $tw.config.contentTypeInfo.',
  '// Maps tiddler type → { encoding, extension } for determining on-disk file format.',
  '// This is generated at build time by extracting the registerFileType() registrations',
  '// from the bundled TW core, so plugin-added types are automatically included.',
  '',
  `// Generated: ${new Date().toISOString()}`,
  `// TiddlyWiki version: ${$tw.version}`,
  '',
  'export interface ContentTypeInfoEntry {',
  "  encoding: 'utf8' | 'base64' | 'utf16le';",
  "  /** File extension with leading dot (e.g. '.tid', '.md', '.png'). May be an array. */",
  '  extension: string | string[];',
  '}',
  '',
  'const contentTypeInfo: Record<string, ContentTypeInfoEntry> = {',
  ...entries.map(e => e + ','),
  '};',
  '',
  'export default contentTypeInfo;',
  '',
  '/**',
  ' * Get the file extension (with leading dot, e.g. `.tid`, `.md`) for a tiddler type.',
  " * Falls back to '.tid' for unknown or untyped tiddlers.",
  ' */',
  'export function getExtensionForType(tiddlerType: string | undefined): string {',
  '  if (!tiddlerType) return \'.tid\';',
  '  const entry = contentTypeInfo[tiddlerType] as ContentTypeInfoEntry | undefined;',
  '  if (!entry) return \'.tid\';',
  '  return Array.isArray(entry.extension) ? entry.extension[0] : entry.extension;',
  '}',
  '',
  '/**',
  ' * Whether a tiddler type stores body and metadata as separate files.',
  ' * Desktop TW writes .tid as self-contained (header+body), and every other',
  " * extension as body-only + .meta companion.",
  ' */',
  'export function usesSeparateMetaFile(tiddlerType: string | undefined): boolean {',
  "  return getExtensionForType(tiddlerType) !== '.tid';",
  '}',
  '',
  '/**',
  " * Get the file encoding for a tiddler type's body file.",
  ' * Desktop TW passes this to fs.writeFile for binary-safe writes.',
  " * Falls back to 'utf8' for unknown types.",
  ' */',
  "export function getTypeEncoding(tiddlerType: string | undefined): 'utf8' | 'base64' {",
  '  if (!tiddlerType) return \'utf8\';',
  '  const entry = contentTypeInfo[tiddlerType] as ContentTypeInfoEntry | undefined;',
  '  if (!entry) return \'utf8\';',
  "  return entry.encoding === 'base64' ? 'base64' : 'utf8';",
  '}',
  '',].join('\n');
writeFileSync(contentTypeInfoPath, tsContent, 'utf8');
console.log(`Wrote ${contentTypeInfoPath} (${Object.keys(contentTypeInfo).length} entries)`);

console.log('Done!');

