name: Build AAB

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - 'wiki/**'
      - 'public/**'
      - 'scripts/**'
      - '.vscode'
      - '.idea'
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - 'README.md'
      - 'wiki/**'
      - 'public/**'
      - '.scripts/**'
      - '.vscode'
      - '.idea'

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: pnpm
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Gradle # fix `incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.`
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.1 # use the gradle version I saw on eas build's console, which might match the kotlin version?
      - name: Set Build Tools Version
        run: |
          echo "BUILD_TOOLS_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | sort -V | tail -n 1)" >> $GITHUB_ENV
        

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Fix gradle error
        run: pnpm exec zx scripts/fix-gradle.mjs

      ## configure cash for gradle : will help to reduce build time
      - uses: actions/cache@v4
        name: Cache Gradle Wrapper and Dependencies
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build tw plugins & scripts
        run: |
          cd plugins && pnpm i && cd ..
          pnpm run build:plugin
          pnpm run build:preload

      - name: Build by eject eas and remove debug signing key for aab
        run: |
          pnpm exec expo prebuild -p android --clean
          pnpm exec zx scripts/removeDebugSigningConfigs.mjs

      - name: Build AAB
        run: |
          cd android
          ./gradlew clean
          ./gradlew bundleRelease --no-daemon --warning-mode all

      - name: Sign AAB
        id: sign_app_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY_UPLOAD }}
          alias: ${{ secrets.ANDROID_ALIAS_UPLOAD }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_PASSWORD_UPLOAD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD_UPLOAD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}
      - name: Rename AAB
        run: mv android/app/build/outputs/bundle/release/app-release.aab android/app/build/outputs/bundle/release/app-release-signed.aab
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          files: android/app/build/outputs/bundle/release/app-release-signed.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
